### ISSUE TITLE
Ложные срабатывания проверок

### ISSUE THREAD

**Issue by Satran87** [Satran87/Doctrina#1]
IsQuestionEnAllList() - сейчас смотрит на 1 лист, надо переделать на все документы

**Comment by Quietmax** [comment]
Я уточнить про ! хочу. Тема с ним такая что файлы с меткой ! в названии(Пример: Э1_Д_23!) должен в файл печати попадать по количеству раз на ровне с остальными, но в этом файле печати, в котором условно 3 или 4 документа на разных листах не должно быть 2 файлов или сказать более одного файла с меткой ! в названии.

**Comment by Satran87** [comment]
Так же сделать проверку на файлы с "!"

**Comment by Satran87** [comment]
Сделал общую проверку на ошибки.

**Comment by Quietmax** [comment]
Серег, привет. Был очень занят. поэтому в реале не было возможности потестить программу. 
Вот из последнего: последнюю версию программы пока запустить на печать не удалось, печатать не дает. Сначала ругалась на то что не совпадение количество условий с количеством решений. Далее я понял что ругается она на что в папках файлы с ! на конце, после удаления их из базы, она открыла файлы для печати, но печатать не дала. лог вышлю на почту. 
В общем затык теперь еще в следующем. В папке с файлами теперь есть 4 типа индексов (!,%,+,-) в конце файла, для того чтобы эти файл с одинаковым индексом на конце не попадали в 1 документ.
То есть в один документ с разными индексами попадать могут, а вот с одинаковыми индексами не должны. Пример: а) 1 документ(Э1_Д_1!, Э1_Д_3%, Э1_Д_10+, Э1_Д_43-) - Норма,
б) 1 документ(Э1_Д_1!, Э1_Д_5!, Э1_Д_54%, "1_L_32%/

Вот эта последняя хотелка появилась буквально в четверг. 

Да и нужно подвести итог, сколько будет стоит нам твоя итоговая работа? Начальство спрашивает.
