### ISSUE TITLE
Хотелки2

### ISSUE THREAD

**Issue by Satran87** [Satran87/Doctrina#3]
Вот из последнего: последнюю версию программы пока запустить на печать не удалось, печатать не дает. Сначала ругалась на то что не совпадение количество условий с количеством решений. Далее я понял что ругается она на что в папках файлы с ! на конце, после удаления их из базы, она открыла файлы для печати, но печатать не дала. лог вышлю на почту. 
В общем затык теперь еще в следующем. В папке с файлами теперь есть 4 типа индексов (!,%,+,-) в конце файла, для того чтобы эти файл с одинаковым индексом на конце не попадали в 1 документ.
То есть в один документ с разными индексами попадать могут, а вот с одинаковыми индексами не должны. Пример: а) 1 документ(Э1_Д1!, Э1Д3%, Э1Д10+, Э1Д43-) - Норма,
б) 1 документ(Э1Д1!, Э1Д5!, Э1Д_54%, "1_L_32%/

Вот эта последняя хотелка появилась буквально в четверг.

**Comment by Satran87** [comment]
Добавил\поправил. Надо бы проверить как будет работать.

**Comment by Quietmax** [comment]
Количество вопросов и ответов совпадает, но у вопроса я только ставил !, а у ответа ничего нет. 
Пример: Э1_Д_1У!/Э1_Д_1Р, с остальными отметками на конце та же история.
А с принтером все ок! Все печатает без проблем.
Версию проверю, сразу отпишу. Чуть позже.

**Comment by Quietmax** [comment]
Решил проверить не отходя от кассы, пишет что опять количество вопросов не совпадает с количеством ответов. Даже если убираю все задачи с индексами на конце, он мне вообще ничего не открывает. Открываешь папку , а он на это только молчит.
Да и правильно, сюда пишу?

**Comment by Satran87** [comment]
Да сюда )
Исходно договоренность была такая:
Количество вопросов=Количество ответов. Имена одинаковые, различия только в Р\У на конце
Соответственно при таком подходе Э1_Д1У!/Э1Д_1Р работать ничего и не будет нормально.
Должно быть Э1__Д1У!/Э1Д_1Р!
Ты на всякий удали "FileList.csv" в папке с вопросами. 
И если будет проявляться, приложи папку, на которой можно проявить.

**Comment by Quietmax** [comment]
Сообщения на мэйл приходят из Git.
Даже после исправления новая сборка не хочет работать, старая версия на той неделе работает.

**Comment by Quietmax** [comment]
Да и тебе это трудно будет исправить. Что работало с теми именами как сейчас, что ! стоит только в названии условия? Если да, то исправить могу и я.

**Comment by Quietmax** [comment]
В общем сборка от 15 работает нормально, но относительно если ставишь все файлы печатать то работает, а если только вопросы то не хочет печатать.Следующие версии печатать  не хотят. Последняя сначала ругается (Количество вопросов и ответов не совпадает), но при этом файлы появляются в списке(окошко справа), Далее настроив параметры печати, жму запуск появляется сообщение( Ошибка комбинации возможных вариантов. Проверьте вводимые данные и количество доступных вопросов) и в журнале последнее сообщение (Вопросов_на_лист=4 | Макс_повторов_вопросов= 12 | Всего_листов= 1)
Файлы для проверки вышлю на почту.

**Comment by Satran87** [comment]
Будут файлы, посмотрим. + Еще приложи FileList.csv и укажи Ограничение по времени.

**Comment by Quietmax** [comment]
Ограничение ставил до 1.11 а файлы выслал тренировочные. Также выслал filelist.

**Comment by Quietmax** [comment]
Да кстати, я уже поправил, чтобы окончания, у файлов условия и решения были одинаковые. У! и Р!

**Comment by Satran87** [comment]
Я только не понял
документ(Э1_Д1!, Э1Д3%, Э1Д10+, Э1Д43-) - Норма
Так ведь и сейчас в одном документе не может быть повторяющихся вопросов.
...
Или имелось в виду что на все документы, которые печатаем должен быть только один документ с символом !,%,+,- на всю очередь печати.

**Comment by Satran87** [comment]
Понял. 1 на документ. Вне зависимости от самого вопроса. В письме от 20 05 поправленная версия.

**Comment by Quietmax** [comment]
Привет, вот журнал новой версии: 
20.10.2015 9:27:15:Окно ввода пароля закрыто
20.10.2015 9:27:57:Ошибка комбинации возможных вариантов 

Проверьте вводимые данные и количество доступных вопросов
20.10.2015 9:27:57:Вопросов_на_лист=4 | Макс_повторов_вопросов= 10 | Всего_листов= 2
20.10.2015 9:28:13:Ошибка комбинации возможных вариантов 

Проверьте вводимые данные и количество доступных вопросов
20.10.2015 9:28:13:Вопросов_на_лист=4 | Макс_повторов_вопросов= 10 | Всего_листов= 2

**Comment by Quietmax** [comment]
В общем все зашло, открыло но при  нажатии кнопки запуск начал ругаться

**Comment by Satran87** [comment]
А ты проверил то, что при твоих вводимых данных должны собраться указанные вопросы?

**Comment by Quietmax** [comment]
Файлов было около 100 в папке, а я попросил всего два документа с 4 вопросами, по-любому они должны сформироваться.

**Comment by Satran87** [comment]
у тебя 4 уникальных вопроса с возможностью повторить их 2 раза, есть? И как уже говорил. Если думаешь что это ошибка то файлы+FileList.csv  на почту

**Comment by Quietmax** [comment]
Ок. Уникальные есть. 100 уникальных файлов, но скинуть смогу фалов 20-30

**Comment by Quietmax** [comment]
Обратил внимание, что в список он добавляет не все. А только файлы с ! на конце.
Через 5 минут вышлю файлы

**Comment by Quietmax** [comment]
Опять же если печатаю без файлов с !, то все работает

**Comment by Quietmax** [comment]
Отправил

**Comment by Satran87** [comment]
Пойми простую мысль. Я НЕ выкладываю сборки, которые не пашут на файлах, которые есть у меня. Но каждый раз получается что у нас наборы файлов разные. Мы либо отлаживаемся на одном набор, либо мне нужны файлы, на которых не работает иначе я не понимаю, как должен проверять работу Я.
Вот вчерашние файлы и вот работа программы на вчерашних файлах.
http://screencast.com/t/ib6roxHtH

## Всё работает.

Так что уже который раз прошу. Если есть файлы, на которых НЕ РАБОТАЕТ их и высылай.

**Comment by Quietmax** [comment]
Согласен, файлы имеют высокую конфиденциальность. Поэтому нужно чтобы они дальше твоего компа не ушли и вообще о них никто не знал. А после теста их лучше удалить. Заметил одну фишку, нижний колонтитул у всех одинаковый, а должен быть разный, так как там у всех шифр свой, внизу слева. Плюс номер страницы увеличиваются, от 1 до 4, а необходимо чтобы файл не менялся. Я так думаю что это из за механизма, все последующие файлы вставляются в первый, от того и колонтитул не меняется.

**Comment by Quietmax** [comment]
Серег, будет еще сегодня версия или ты занят ?

**Comment by Satran87** [comment]
По загрузке файлов понял что там не так было ("!" в названии папки). Это поправил.
А вот про нижний колонтитул пока думаю.

**Comment by Quietmax** [comment]
То есть ! в названии папке должно быть везде, или теперь оно просто не будет ругаться на такие случаи, мне может проще их удалить?
 Таких папок всего 18.

**Comment by Satran87** [comment]
Забей - это я уже поправил. Теперь что ! что еще какой знак в имени папки, роли не играет.

**Comment by Satran87** [comment]
Так. Переделал систему печати полностью. Теперь колонтитулы должен тащить с собой. 
Ошибку с тем, что не видел часть файлов я поправил. Теперь все присланные тобой файлы видит целиком.

Проверь, будет ли нормально комбинировать\печатать.
Если что еще вылезет - сразу шли комплект файлов (как закончим со всем этим файлы удалю) Вместе с папкой и пиши что не так.

**Comment by Quietmax** [comment]
На почте файлы. Видит все а ругается как и раньше и печатать вообще не хочет, на той последней папке которую отправил. Она лежит в другой папке, может в этом трудность.

**Comment by Satran87** [comment]
Я послал 2 файла.
В 17 10 - это сбойный
в 17 23 - этот нормальный.
даже на 17  23 ругается?
Какой полный путь к папке?
Можешь на почту кинуть?

**Comment by Quietmax** [comment]
C:\Users\User\Desktop\Задачи5-4-3\Общие!\Э_ЗиС!

**Comment by Quietmax** [comment]
ААА,стоп верисии 17,23 не было
пробую ее

**Comment by Satran87** [comment]
я только не понял. Если у нас документ состоит из 4 вопросов. Мы получили, допустим 8 листов (2 вопроса содержали 2 страницы).
То что должно быть с нумерацией страниц? 1-8 или 1\1\1\1\2\2 ?

**Comment by Quietmax** [comment]
можно пока и 1-8, на данном этапе это и лучше. так как не везде правильная нумерация. В идеале должно быть: один вопрос его нумерация 1,2(если 2 страницы в задаче), далее след вопрос, его нумерация 1, 2(если 2 страницы в задаче) и т.д.

**Comment by Quietmax** [comment]
Слушай последняя версия работает. Завтра постараюсь потестить на других документах, тогда и отпишу.

**Comment by Satran87** [comment]
А зачем тогда печатать как один документ? Я к тому, что делаем билет, в котором 3 вопроса. Зачем у каждого вопроса своя нумерация? Разве не логично, что в билете должна быть сквозная?

**Comment by Quietmax** [comment]
Полностью логично, этот вопрос я с начальством уже состыковывал. Последний раз остановились что как выглядит задача в отдельном файле, так и в билете. Пусть остается сквозная. Так и выглядит благороднее.
