### ISSUE TITLE
Хотелка3

### ISSUE THREAD

**Issue by Quietmax** [Satran87/Doctrina#4]
Работает все здорово.
Иногда встречается что последний в документе файл меняется шрифт размер абзаца и размер шрифта, а иногда документ растягивается на несколько страниц, хотя в исходнике один лист.

И собственно сама хотелка: За сессию я могу открыть 4 разных папки - 10 разных папок, в каждой папке я могу выбрать 1 документ - 15 документов на печать, поэтому у меня получается сквозная нумерация по всем папкам. Объясню почему хочется исправить, каждая папка в нашем понимании это область аттестации, на каждой области своя сквозная нумерация и она не как не коррелируется с общим числом задач по всем областям, которых 90.  В идеале хотелось чтобы создавались папки с датой а в ней были документы с названием, который состоит из последних папок, имя должно начинаться с предпоследней папки в пути. А в ней файл со списком печати в какой документ какие задачи пошли из этой папки. И тогда не нужно вставлять какая папка в каждую строку документа.

И последнее добавились еще знаки отличия для задач которые не должны с одним и тем же символом на конце попадать в один документ, это # и ; и @ и &

**Comment by Satran87** [comment]
По ошибке - нужны файлы на которых проявляется.
....
 В идеале хотелось чтобы создавались папки с датой а в ней были документы с названием, который состоит из последних папок, имя должно начинаться с предпоследней папки в пути. А в ней файл со списком печати в какой документ какие задачи пошли из этой папки
....
т.е. C:\Папка1\Папка2\Папка3\

Создается папка "PrintStatistics\ТекущаяДата\Папка2\ФайлСоСписокПечати.csv"?

А это о чём?
"а в ней были документы с названием"
Исходно договоренность была что документы только печатаем, не сохраняем, разве нет?

**Comment by Satran87** [comment]
В любом случае нужен пример пути + пример имён папок\их расположения друг относительно друга (тут про то что мне генерировать)
Так не до конца ясно что требуется.

**Comment by Quietmax** [comment]
Хорошо, буду теперь ловить и посылать тебя файлы. 

Вот на данный момент путь к файлам печати: C:\Users\User\Desktop\Задачи5-4-3\Э1!\ТУ

А хочется чтобы файлы отчетности были в : "PrintStatistics\Э1!\ТУ\ФайлСоСписокПечати.csv"?

В файле нумерация сквозная документов. Каждый раз когда я начну печатать снова из этой папке в этот файл попадают список документов, с разложением какие задачи в него попали, продолжая нумерацию.

Привязка к дате не обязательна.

**Comment by Quietmax** [comment]
Привязка к дате не обязательна.

**Comment by Satran87** [comment]
Сделал имя статичным. 
Сделал запись в папки с нужными именами.

По файлу статистики, учти, что т.к. теперь имя статичное, 
то 65 тыщ строк ограничение - раз
когда станет весить много(10-100 мб, если доведете), то и открываться будет долго (пару сек минимум), а это будет подтормаживать прогу.

**Comment by Quietmax** [comment]
На сколько я понял что удалил и дальше шпарь)

**Comment by Satran87** [comment]
Удалил\переместил и да, полегчает.
